name: Release Homebrew

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag name
        required: true
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  homebrew:
    if: github.repository == 'dita-ot/dita-ot' && (github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Set tag name
        run: |
          echo "tag=${{ inputs.tag || github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
      - name: Create pull-request
        uses: mislav/bump-homebrew-formula-action@v4.2
        with:
          formula-name: dita-ot
          tag-name: ${{ env.tag }}
          base-branch: main
          download-url: https://github.com/dita-ot/dita-ot/releases/download/${{ env.tag }}/dita-ot-${{ env.tag }}.zip
          commit-message: |
            {{formulaName}} {{version}}

            Created via GitHub Action
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_COMMITTER_TOKEN }}
