name: Release test
on:
  push:
    branches:
      - "release/**"
      - "hotfix/**"
jobs:
  distribution:
    if: ${{ github.repository == 'dita-ot/dita-ot' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Set tag name
        run: |
          echo "tag=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV
      - name: Build distribution package
        run: |
          ./gradlew --no-daemon
          ./gradlew dist -Pcommit=${GITHUB_SHA} -Ptag=${TAG} --no-daemon
        env:
          TAG: ${{ env.tag }}
      - name: Extract distribution package
        run: |
          unzip build/distributions/dita-ot-${TAG}.zip -d build/distributions/
      - name: Test HTML5 and PDF2
        run: |
          ./bin/dita -i docsrc/userguide.ditamap -f html5 -f pdf2 -o out -v
        working-directory: build/distributions/dita-ot-${TAG}
